/** @type {import('ts-jest/dist/types').InitialOptionsTsJest} */
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  collectCoverage: false,
  collectCoverageFrom: [
    '**/*.{js,ts}',
    '!**/dist/**',
    '!**/*.d.ts',
    //e2e",
    '!**/e2e/**/*',
    //unit test related",
    '!tests/**',
    '!**/*.test.*',
    '!**/*__test*?__*/**/*',
    '!**/coverage*/**/*',
    '!**/__data__/**/*',
    '!**/*.test.*/**/*',
    // ui related",
    '!**/*.{jsx,tsx}',
    // data MOCK",
    '!**/__mock*/**/*',
    '!**/_mock*/**/*',
    '!**/*__mock?__*/**/*',
    '!**/mocks?/**/*',
    // monitoring",
    '!**/monitor*',
    '!**/monitor/**/*',
    // root directory",
    '!dist/**/*',
    '!build/**/*',
    '!doc?/**/*',
    '!**/.*/*',
    '!*.*',
    '!.*',
    // scripts related",
    '!**/scripts/**/*',
    // third-party SDK",
    '!**/__sdk__/**/*',
    '!**/lib/**/*',
    // constants",
    '!**/__text__/**/*',
    '!**/constants/**/*',
    '!**/constants.{js,ts}',
    // api interfaces
    '!**/__api__/**/*',
    '!**/service?/**/*',
    '!**/service/**/*',
    // SSR
    '!**/*.server.*',
    // TS definitions
    '!**/types/**/*.ts',
    '!**/*.d.ts',
    // i18n
    '!**/i18n/**/*',
    '!**/i18n*.{js,ts}',
    // config files
    '!**/*.config.{js,ts}',
    '!**/config?/**/*',
    '!**/config/**/*',
    '!**/__config__/**/*',
    // deprecated and unmaintained
    '!**/deprecated/**/*',
    '!**/*_deprecated/**/*',
    // demo related
    '!**/demos/**/*',
    '!**/demo/**/*',
    '!**/_?demo*/**/*',
    '!**/__demo*/**/*',
    // others
    '!**/*.html',
    // pure UI rendering
    '!**/*_pureRender/**/*',
    '!**/pureRender/**/*',
    // multi-site related
    '!**/src/site/**/*',
  ],
  coverageDirectory: '<rootDir>/coverage',
  coverageReporters: ['text', 'lcov', 'html', 'json'],
  coverageThreshold: {
    global: {
      branches: 60,
      // functions: 70,
      lines: 70,
      // statements: 70,
    },
  },
  setupFilesAfterEnv: ['<rootDir>/../../jest.setup.js'],
  testTimeout: 30000,
};
